name = "OpenStreetMapXPlot"
uuid = "d3d4fdd0-c191-11e8-3358-a3629b56487d"
authors = ["Przemyslaw Szufel <pszufe@gmail.com>", "Bartosz Pankratz <bartosz.pankratz@gmail.com>", "Anna Szczurek <annaszczurek2@gmail.com>", "Bogumil Kaminski <bogumil.kaminski@gmail.com>", "Pawel Pralat <pralat@ryerson.ca>"]
version = "0.1.5"

[deps]
OpenStreetMapX = "86cd37e6-c0ff-550b-95fe-21d72c8d4fc9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
OpenStreetMapX = "0.1.12, 0.2, 0.3.1, 0.4.0"
Plots = "^1.5.0"
PyPlot = "^2.9.0"
Random = "^1.6.0"
julia = "^1.6.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
